workspace:
  base: /drone/src
  path: vaadin-developer-demo-corejava

pipeline:
  build:
    image: ${JDK_VERSION}
    pull: true
    commands:
      - mkdir /root/.m2
      - cp /drone/src/vaadin-developer-demo-corejava/_data/nexus/settings.xml /root/.m2/settings.xml
      - mvn clean
      - mvn install

matrix:
  JDK_VERSION:
  - svenruppert/maven-3.5-jdk-08
  - svenruppert/maven-3.5-jdk-09
  - svenruppert/maven-3.5-jdk-10
  - svenruppert/maven-3.5-jdk-11
  - svenruppert/maven-3.5-jdk-graalvm-ce-01
  - svenruppert/maven-3.5-jdk-oracle-08
  - svenruppert/maven-3.5-jdk-oracle-09
  - svenruppert/maven-3.5-jdk-oracle-10
  - svenruppert/maven-3.5-jdk-zulu-08
  - svenruppert/maven-3.5-jdk-zulu-09
  - svenruppert/maven-3.5-jdk-zulu-10
  - svenruppert/maven-3.5-jdk-ibm-08
#  - svenruppert/maven-3.5-jdk-ibm-09
  - maven:3.5-ibmjava-8-alpine
  - maven:3.5-ibmjava-9-alpine

